
CREATE TABLE  music_store.instruments (
  id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  sku VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  unit_price BIGINT(20) DEFAULT NULL,
  image_url VARCHAR(255) DEFAULT NULL
)
